name: Monthly Submodule Update

on:
    schedule:
        - cron: "0 0 1 * *" # every 1st of month
    workflow_dispatch: # allows manual trigger

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Update submodules to latest
              run: |
                  git submodule update --remote --merge

            - name: Commit changes if any
              run: |
                  git config user.name "github-actions"
                  git config user.email "actions@github.com"
                  git add .
                  git commit -m "Monthly submodule update" || echo "No changes"

            - name: Push changes
              run: |
                  git push
